name: CI (merge)

on: 
  merge_group:

permissions:
  contents: write # to upload assets to releases

jobs:
  ci:
    runs-on: ubuntu-latest

    name: CI

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Install pip dependencies
      run: pip install -r requirements.txt -r scripts/pdf/requirements.txt

    - name: Test
      run: npm test

    - name: Build
      run: bash scripts/build.sh

    - name: Build PDF
      if: github.repository == 'kbdkorg/tldr'
      working-directory: ./scripts/pdf
      run: bash build-pdf.sh

    - name: Deploy
      if: github.repository == 'kbdkorg/tldr'
      run: bash scripts/deploy.sh
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
