name: Copy assets to the new release

on:
  release:
    types: published

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Copy assets to the new release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to upload assets to releases
      attestations: write # to upload assets attestation for build provenance
      id-token: write # grant additional permission to attestation action to mint the OIDC token permission

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download assets
        run: |
          LATEST="$(git describe --tags --abbrev=0)"
          PREVIOUS="$(git describe --tags --abbrev=0 "$LATEST"^)"

          mkdir release-assets && cd release-assets

          gh release download "$PREVIOUS"
      
      - name: Attest copied assets
        working-directory: release-assets
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: *.zip, *.pdf, index.json, tldr.sha256sums

      - name: Upload assets
        working-directory: release-assets
        run: gh release upload "$LATEST" -- *
